### ISSUE TITLE
Do you have any demo project?

### ISSUE THREAD

**Issue by kiwo12345** [kfirba/Directo#1]
Do you have any demo project including JS code that you can share? :)

**Comment by rafapaulin** [comment]
`InvalidArgumentBucket POST must contain a field named 'key'. If it is specified, please check the order of the fields.`

any idea what could be wrong?

**Comment by kfirba** [comment]
@rafapaulin Hey.

Can you use your browser element inspection tool and see what hidden elements you have in your form? You should have an input like that:

```
<input type="hidden" name="key" value="${filename}">
```

**Comment by kfirba** [comment]
Closed due to inactivity. If it's still relevant, leave a comment,
