### ISSUE TITLE
Fineuploader integration issue

### ISSUE THREAD

**Issue by ghost** [kfirba/Directo#3]
thank you for this package,

Iam using Fineuploader's s3 mode and Iam generating the **signature** and **policy** (endpoint) for V4 on backend using this package, and this package uses its own policy inputs when singing the policy:

```php
$policy = [
            'expiration' => $this->expirationDate(),
            'conditions' => [
                ['bucket' => $this->bucket],
                ['acl' => $this->options->acl],
                ['starts-with', '$key', $this->options->valid_prefix],
                [$contentTypePrefix, '$Content-Type', $this->options->content_type],
                ['content-length-range', 0, $this->mbToBytes($this->options->max_file_size)],
                ['success_action_redirect' => $this->options->success_action_redirect],
                ['success_action_status' => $this->options->success_action_status],
                ['x-amz-credential' => $this->credentials->AMZCredentials()],
                ['x-amz-algorithm' => 'AWS4-HMAC-SHA256'],
                ['x-amz-date' => gmdate('Ymd\THis\Z', $this->time)]
            ]
        ];
```
Fineuploader by **default** will set request payload for the file Iam trying to upload ( which is different from the policy I signed using this package): 

    {"expiration":"2018-03-16T09:10:45.082Z",
    "conditions":
    \[{"acl":"private"},
    {"bucket":"bucket-name"},
    {"Content-Type":"image/jpeg"},
    {"success\_action\_status":"200"},
    {"x-amz-algorithm":"AWS4-HMAC-SHA256"},
    {"key":"37f86eae-46e9-4047-91c1-c8ee2cbf90b6.jpg"},
    {"x-amz-credential":"GWRQRFFXBA3C3S7GOVQQ/20180316/eu-central-1/s3/aws4\_request"},
    {"x-amz-date":"20180316T090545Z"},
    {"x-amz-meta-qqfilename":"JPG-GG\_400x400.jpg"},
    \["content-length-range","0","23424"\]\]}

so for example , Fineuploader will set **x-amz-date**: 20180316T090545Z in request payload for the file and this package will set some different value for **x-amz-date**, so when I try to upload the file I will face many errors, like:
policy doesn't match ... etc ..

Is there any workaround?

**Comment by kfirba** [comment]
@Rux77 I see. So basically Fineuploader will generate its own policy and send it to the backend to just sign the policy. Currently, Directo implementation isn't capable of doing that. Directo will create a new policy based on global configurations and will use the current time for the signature.

How about we introduce a new method on the Directo object that will sign policies? Maybe something like:

```php
Directo::sign($policy);
// ['policy' => 'base64_encoded_policy, 'signature' => '...']
```

**Comment by kfirba** [comment]
@Rux77 I've just pushed a new version that will let you sign a given policy.

You can now call a `sign()` method off of the Directo object which will sign a given json or base64-encoded policy.

**Comment by ghost** [comment]
@kfirba 
Yes , thank you.

just a question ( Iam still learning s3 and Fineuploader) : 
from security point .. Is this safe thing to do? because in the client-end someone can maybe change values like: 
[{"acl":"private"}, and make it [{"acl":"public-read"}, before sending this policy to backend for signing.
